name: messenger
description: A messenger applicaiont power by Firebase / Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rive: ^0.9.1
  uuid: ^3.0.7
  intl: ^0.17.0
  provider: ^6.0.4
  go_router: ^5.2.4
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  image_cropper: ^3.0.1
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  image_picker: ^0.8.6+1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  cloud_functions: ^4.0.7
  cloud_firestore: ^4.3.1
  json_serializable: ^6.5.4
  animated_text_kit: ^4.2.2
  firebase_storage: ^11.0.10
  firebase_database: ^10.0.8
  firebase_messaging: ^14.2.0
  firebase_analytics: ^10.0.7
  shared_preferences: ^2.0.15
  flutter_colorpicker: ^1.0.3
  flutter_svg_provider: ^1.0.3
  firebase_crashlytics: ^3.0.7
  flutter_keyboard_visibility: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
  assets:
    - assets/rive/
    - assets/image/
    - assets/icon/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/message_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/message_icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/message_icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/message_icon.jpg"
